/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Map;



/**
 *
 * @author Małgorzata
 */
public class JurassicParkMap extends javax.swing.JFrame {

    /**
     * Creates new form JurrasicParkMap
     */
    public JurassicParkMap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JurassicParkTitle = new javax.swing.JLabel();
        JurassicParkGetStarted = new javax.swing.JButton();
        startLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        JurassicParkTitle.setBackground(new java.awt.Color(0, 0, 0));
        JurassicParkTitle.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        JurassicParkTitle.setForeground(new java.awt.Color(255, 255, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Map/Bundle"); // NOI18N
        JurassicParkTitle.setText(bundle.getString("JurassicParkMap.JurassicParkTitle.text")); // NOI18N
        JurassicParkTitle.setName("JurassicParkTitle"); // NOI18N

        JurassicParkGetStarted.setIcon(new javax.swing.ImageIcon("C:\\Users\\Małgorzata\\Downloads\\Jurassic_Park_(franchise_logo).png")); // NOI18N
        JurassicParkGetStarted.setToolTipText(bundle.getString("JurassicParkMap.JurassicParkGetStarted.toolTipText")); // NOI18N
        JurassicParkGetStarted.setName("JurassicParkGetStarted"); // NOI18N

        startLabel.setBackground(new java.awt.Color(0, 0, 0));
        startLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        startLabel.setForeground(new java.awt.Color(255, 255, 51));
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLabel.setText(bundle.getString("JurassicParkMap.text")); // NOI18N
        startLabel.setToolTipText(bundle.getString("JurassicParkMap.toolTipText")); // NOI18N
        startLabel.setName(""); // NOI18N
        startLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JurassicParkTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JurassicParkGetStarted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JurassicParkTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JurassicParkGetStarted)
                .addGap(18, 18, 18)
                .addComponent(startLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JurassicParkMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JurassicParkMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JurassicParkMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JurassicParkMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JurassicParkMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JurassicParkGetStarted;
    private javax.swing.JLabel JurassicParkTitle;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables
}
